pypi:
    image:
        name: pretix/ci-image
    script:
        - cat $PYPIRC > ~/.pypirc
        - pip install -U pip uv
        - uv pip install --system -U wheel setuptools
        - uv pip install --system -Ur requirements_dev.txt
        - python setup.py develop
        - python setup.py sdist bdist_wheel
        - twine check dist/*
        - twine upload dist/*
    only:
        - pypi
    artifacts:
        paths:
            - dist/
